### ISSUE TITLE
PNA-Project2

### ISSUE THREAD

**Issue by Tsumida** [Tsumida/rskvs#1]
# Project-2
Project2: https://github.com/Tsumida/talent-plan/blob/master/rust/projects/project-2/README.md
Building blocks 2: https://github.com/Tsumida/talent-plan/blob/master/rust/building-blocks/bb-2.md

## TODO
- [x] Part 1: Error handling
- [x] Part 2: How the log behaves
- [x] Part 3: Writing to the log
- [x] Part 4: Reading from the log
- [x] Part 5: Storing log pointers in the index
- [x] Part 6: Stateless vs. stateful KvStore
- [x] Part 7: Compacting the log
- [x] Add path setting for cli.

## testing
- [x] CLI testing.
- [x] DB functionality testing.
- [x] Log compaction

## log compaction
maintain data-integrity if compaction fails.
